envs: 16
dt: 0.0025
steps: 1000 # 动力学仿真脚本使用
device: cuda

# 负载参数
m_l: 3.0                  # 负载质量 (kg)
J_l: 6                 # 负载转动惯量 (kg⋅m²)
r_g: [0, 0, 0]         # 负载重心偏移
g: 10                   # 重力加速度
r_payload: 0.25        # 负载半径 (m)

# 绳子参数
rope_num: 6
rope_length: 1.0          # 绳长 (m)
rl : 0.25                 # 绳子连接点圆的半径

# 绳子初始张力
cable_initial_tensions: 5       # 初始张力 (N) - 平衡负载重量

#无人机半径
drone_radius: 0.125         # 无人机半径 (m)
# 障碍物参数
obstacle_pos:             # 障碍物位置 (只有x,y坐标，z假设为负载高度)
  - [1.5, 1.3]
  - [0.4, 2.9]
obstacle_r: 0.5           # 障碍物半径 (m)

# 在你的config文件中添加这些参数
pos_weight: 1.5          # 位置权重
vel_weight: 0.4          # 速度权重
quat_weight: 0       # 姿态权重
omega_weight: 0      # 角速度权重

pos_reward_scale: 1    # 位置误差缩放（值越大，对误差越敏感）
vel_reward_scale: 1   # 速度误差缩放
quat_reward_scale: 0.1  # 姿态误差缩放
omega_reward_scale: 0.1  # 角速度误差缩放

progress_reward: 0.2     # 轨迹进展奖励
collision_penalty: -10.0 # 碰撞惩罚
target_threshold: 0.1    # 到达目标的距离阈值 (m)

# 终止条件
collision_tolerance: 0.01 # 碰撞容忍度 (m)
drone_high_distance: 0.01 # 无人机碰撞高度检测
t_max: 50.0               # 最大绳子张力 (N)
pos_error_threshold: 0.15 # 位置误差阈值
pos_error_count: 5       # 连续位置误差超过阈值的步